apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: class-exercise
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password123"
  MONGO_URI: "mongodb://root:password123@mongo:27017/todo?authSource=admin"
