apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: class-exercise
data:
  MONGO_DB: "todo"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  API_BASE: "/api"
  APP_TITLE: "Kubernetes Class App"
