apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: class-exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: class-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: API_BASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: API_BASE
        - name: APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_TITLE
