apiVersion: v1
kind: Pod
metadata:
  name: block-pod1
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:  # Not volumeMounts
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc