apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab-networking
  name: ubuntu-app
spec:
  selector:
    matchLabels:
      app: ubuntu-app
  template:
    metadata:
      labels:
        app: ubuntu-app
    spec:
      containers:
      - name: ubuntu-app
        image: ubuntu
        command: ["sleep","4000"]