apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: pizza
spec:
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: pizza-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
         - name: DB_PORT
           valueFrom:
             configMapKeyRef:
               name: pizza-config
               key: port
         - name: DB_PASSWORD
           valueFrom:
             secretKeyRef:
               name: db-secrets
               key: db-password
         - name: DB_USER
           valueFrom:
             secretKeyRef:
               name: db-secrets
               key: db-user
         - name: DB_HOST
           valueFrom:
             configMapKeyRef:
               name: pizza-config
               key: host
         - name: DATABASE
           valueFrom:
             configMapKeyRef:
               name: pizza-config
               key: database